//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISBank_Assessment.BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Accounts = new HashSet<Account>();
            this.CustomerContacts = new HashSet<CustomerContact>();
            this.Loans = new HashSet<Loan>();
        }
    
        public int CustomerId { get; set; }
        public int CustomerType { get; set; }
        public int Status { get; set; }
        public string AccountNumber { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public string IDNumber { get; set; }
        public string PassportNumber { get; set; }
        public string PreferredLanguage { get; set; }
        public string Email { get; set; }
        public string MobileNumber { get; set; }
        public string LandLineNumber { get; set; }
        public string AlternateNumber { get; set; }
        public string BillingAddress1 { get; set; }
        public string BillingAddress2 { get; set; }
        public string BillingAddress3 { get; set; }
        public string BillingAddress4 { get; set; }
        public string BillingPostalCode { get; set; }
        public string PhysicalAddress1 { get; set; }
        public string PhysicalAddress2 { get; set; }
        public string PhysicalAddress3 { get; set; }
        public string PhysicalAddress4 { get; set; }
        public string PhysicalPostalCode { get; set; }
        public string Region { get; set; }
        public string CompanyName { get; set; }
        public string CompanyType { get; set; }
        public string CompanyDescription { get; set; }
        public string RegNumber { get; set; }
        public string VATNumber { get; set; }
        public string ExternalAccountNumber { get; set; }
        public string Remarks { get; set; }
        public string Classification { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public System.DateTime LastModifiedByDate { get; set; }
        public byte[] TimeStamp { get; set; }
        public string PostalCode { get; set; }
        public int Code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerContact> CustomerContacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Loan> Loans { get; set; }
    }
}
