//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISBank_Assessment.BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmploymentDetail
    {
        public int EmploymentDetailsId { get; set; }
        public string Income { get; set; }
        public string Job { get; set; }
        public string Title { get; set; }
        public string Employer { get; set; }
        public Nullable<int> CustomerContactId { get; set; }
    
        public virtual CustomerContact CustomerContact { get; set; }
    }
}
